name: saints-license-server

services:
  - name: api
    github:
      repo: boogz0217/saints-gen-bot
      branch: main
      deploy_on_push: true
    run_command: python main.py
    http_port: 8000
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: DISCORD_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: GUILD_ID
        scope: RUN_TIME
        value: "1290387028185448469"
      - key: SUBSCRIBER_ROLE_ID
        scope: RUN_TIME
        value: "1466912099585364130"
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ADMIN_IDS
        scope: RUN_TIME
        value: "1015259363478339644"
      - key: STORE_URL
        scope: RUN_TIME
        value: "https://saintservice.store/"
      - key: PRIVATE_KEY_B64
        scope: RUN_TIME
        type: SECRET
      - key: SAINTS_SHOT_ROLE_ID
        scope: RUN_TIME
        type: SECRET
      - key: DISCORD_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: DISCORD_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: SHOPIFY_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: DISCORD_REDIRECT_URI
        scope: RUN_TIME
        type: SECRET
      - key: APP_URL
        scope: RUN_TIME
        type: SECRET
